### ISSUE TITLE
WebView2_spec: Missing WebResourceRequested event?

### ISSUE THREAD

**Issue by Arlodotexe** [microsoft/microsoft-ui-xaml-specs#65]
After looking through the specs for the upcoming WebView2, it seems that the `WebResourceRequested` event is missing. Are there plans to implement this? 

This API is especially handy, and the only alternative is injecting an override wrapper for `fetch` and Ajax requests, which catches the Javascript requests, but not the resources declared in the DOM or CSS.

**Comment by jesbis** [comment]
@adambarlow can confirm but I believe this will be exposed via a projection of the core WebView [`iwebview2webview5::add_WebResourceRequested`](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview5#add_webresourcerequested)
interface which just hasn't been projected yet, per the proposal notes in https://github.com/microsoft/microsoft-ui-xaml/issues/1658:

> Additional APIs will reside on the WebView2 core object. There are not represented in the API spec linked above. In short; If you don't see an API in the WebView2 API spec and it is existing functionality of the current WebView, it is likely planned to be included on the base WinRT object, whose API is likely to closely match the current IWebView2WebView interface.

**Comment by adambarlow** [comment]
Yes, thank you @jesbis , that is correct.
