### ISSUE TITLE
WebView2_spec: Missing PermissionRequested

### ISSUE THREAD

**Issue by mykebates** [microsoft/microsoft-ui-xaml-specs#66]
Forgive me if this is the wrong place to add this. Just pulled down the latest WinUI 3.0 Alpha (February 2020) bits to start kicking the tires with WebView2. I noticed PermissionRequested is not available. Not sure if this is still the proper way to handle permission granting for things like UserMedia access?

Is this currently scoped, or is there a different way to handle granting permissions?

**Comment by adambarlow** [comment]
Thanks for testing it out. As stated in the release notes many of the APIs previously situated on the XAML WebView element are not going to sit on the core WinRT object, whose API will match what we are seeing on the current [IWebView2 interface](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference-webview2).
