### ISSUE TITLE
Window & CoreWindow name conflict.

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/microsoft-ui-xaml-specs#86]
I've raised this issue before, but now that you are actually rebuilding the API's it seems like a great time to bring it up again.

Take a look at these names ..

```
Windows.UI.Xaml.Window
Windows.UI.Core.CoreWindow
```

That doesn't read right to me at all. CoreWindow is a type of Window, and Window is a type of Window, but CoreWindow is not a type of Window?

Why don't you choose either a or b pattern as follows ..

a)
```
Windows.UI.Xaml.XamlWindow
Windows.UI.Core.CoreWindow
```

b)
```
Windows.UI.Xaml.Window
Windows.UI.Core.Window
```

Then you have consistency, either adopting specialized names for the respective types. Or a common conceptual name in the respective namespaces. Either option would seem more consistent and would respectively free up either Window or the CoreWindow/XamlWindow name pair for our usage.

It just seems like they were each written by different people who didn't communicate.

And it's especially strange, although I don't know the underlying code, but to me it seems like if anything - CoreWindow would be the underlying Window because it provides the base rendering surface and XamlWindow (what you call Window) would be the child type because it makes sense that you take a Window (with Core functionality) and then render a root control inside that window - the XamlWindow.

And in a future scenario that XamlWindow could be replaced with another type of specialized window model - HttpWindow, FlutterWindow, GameWindow - providing whatever logic/rendering stack you want inside that Window (the container).

**Comment by marb2000** [comment]
@Gavin-Williams Thank you for opening this issue. The decision of keep using these two existing UWP APIs (Windows.UI.Xaml.Window and Windows.UI.Core.CoreWindow) was based of minimize the breaking changes of UWP apps when migrating from UWP XAML to WinUI 3 XAML. This decision was approved by the API Review Board long time ago and we can't change it at this point.

I will close this issue as won't fix. Thank you for your feedback.
